name: train
device: cuda
gpus: [0]
max_epochs: 30

test:
  run: False
  epoch_start: 1
  epoch_step: 5
  run_before_train: False
  run_after_train_with_best: False

inference_video:
  run: False
  epoch_start: 1
  epoch_step: 5
  run_before_train: False
  run_after_train_with_best: False

vis_result: False
vis_hm: False
vis_traj: False

best_model_name: best_model.pth.tar
find_fp1_epochs: []
fp1_filename: fp1_examples.txt


