name: volleyball
root_dir: /root/datasets/volleyball
frame_dirname: videos
csv_dirname: volleyball_ball_annotation 
ext: '.jpg'
train: # cf. https://github.com/wjchaoGit/Group-Activity-Recognition/blob/master/config.py
  matches: [1,3,6,7,10,13,15,16,18,22,23,31,32,36,38,39,40,41,42,48,50,52,53,54,0,2,8,12,17,19,24,26,27,28,30,33,46,49,51] 
  num_clip_ratio: 1.0
test: # cf. https://github.com/wjchaoGit/Group-Activity-Recognition/blob/master/config.py
  matches: [4,5,9,11,14,20,21,25,29,34,35,37,43,44,45,47] 
  num_clip_ratio: 1.0
